# Generated by Django 5.0.1 on 2024-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Prédio', 'verbose_name_plural': 'Prédios'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'Unidade de Produto', 'verbose_name_plural': 'Unidades de Produto'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Compra'),
        ),
    ]
