# Generated by Django 5.0 on 2024-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_productunit_slug_room_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
