# Generated by Django 5.0 on 2024-02-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
