# Generated by Django 5.0.1 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0010_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hall",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="Corredor"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="shelf",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="Prateleira"
            ),
        ),
    ]
