# Generated by Django 5.0.1 on 2024-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0011_room_hall_room_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado"),
        ),
        migrations.AddField(
            model_name="productunit",
            name="write_off",
            field=models.BooleanField(default=False, verbose_name="Baixado"),
        ),
    ]
