# Generated by Django 5.0.1 on 2024-04-19 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0012_productunit_modified_productunit_write_off"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Corredor"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corredor",
                "verbose_name_plural": "Corredores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Prateleira"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prateleira",
                "verbose_name_plural": "Prateleiras",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="productunit",
            options={
                "ordering": ["write_off", "purchase_date", "product"],
                "verbose_name": "Unidade de Produto",
                "verbose_name_plural": "Unidades de Produto",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["building", "name"],
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
            },
        ),
        migrations.AlterField(
            model_name="productunit",
            name="write_off",
            field=models.BooleanField(default=False, verbose_name="Baixado?"),
        ),
        migrations.AlterField(
            model_name="room",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.hall",
                verbose_name="Corredor",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.shelf",
                verbose_name="Prateleira",
            ),
        ),
    ]
