# Generated by Django 5.0.1 on 2024-04-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0013_hall_shelf_alter_productunit_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="shelf",
        ),
        migrations.AddField(
            model_name="hall",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.shelf",
                verbose_name="Prateleira",
            ),
        ),
    ]
