# Generated by Django 5.0.1 on 2024-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0016_alter_stocktransfer_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="meters",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Metros"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productunit",
            name="ncm",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="NCM"
            ),
        ),
    ]
