# Generated by Django 5.0.1 on 2024-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0020_color_pattern_alter_building_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='meters',
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('cm', 'Centímetros'), ('m', 'Metros'), ('g', 'Gramas'), ('kg', 'Quilogramas')], default='m', max_length=2, verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='size_length',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Tamanho / Peso'),
            preserve_default=False,
        ),
    ]
