# Generated by Django 5.0.1 on 2024-05-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_remove_productunit_meters_product_measure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productunit',
            old_name='size_length',
            new_name='weight_length',
        ),
    ]
