# Generated by Django 5.0.1 on 2024-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0022_rename_size_length_productunit_weight_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('cm', 'Centímetros'), ('m', 'Metros'), ('g', 'Gramas'), ('kg', 'Quilogramas')], max_length=2, verbose_name='Medida'),
        ),
    ]
