# Generated by Django 5.0.1 on 2024-05-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0023_alter_product_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('weight_length_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tamanho / Peso Antes')),
                ('weight_length_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tamanho / Peso Depois')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.productunit', verbose_name='Unidade de Produto')),
            ],
            options={
                'verbose_name': 'Consumo de Tecido',
                'verbose_name_plural': 'Consumos de Tecido',
            },
        ),
    ]
