# Generated by Django 5.0.1 on 2024-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0024_clothconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Retornado?'),
        ),
    ]
