# Generated by Django 5.0.1 on 2024-05-03 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0025_productunit_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='returned',
        ),
        migrations.CreateModel(
            name='Write_off',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.TextField(blank=True, null=True, verbose_name='Origem')),
                ('destination', models.TextField(blank=True, null=True, verbose_name='Destino')),
                ('write_off_date', models.DateField(verbose_name='Data de Baixa')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='inventory_management.productunit', verbose_name='Unidade de Produto')),
            ],
            options={
                'verbose_name': 'Baixa de Estoque',
                'verbose_name_plural': 'Baixas de Estoque',
            },
        ),
    ]
