# Generated by Django 5.0.1 on 2024-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_management",
            "0031_building_created_at_building_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="write_off",
            options={"verbose_name": "Baixa", "verbose_name_plural": "Baixas"},
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="code",
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="ncm",
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Composição"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ncm",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="NCM"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Largura",
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="imcoming",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rendimento",
            ),
        ),
    ]
