# Generated by Django 5.0.1 on 2024-05-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0031_building_created_at_building_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='write_off',
            options={'verbose_name': 'Baixa', 'verbose_name_plural': 'Baixas'},
        ),
    ]
