# Generated by Django 5.0.1 on 2024-05-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0033_destinations_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.employee', verbose_name='Funcionário'),
        ),
    ]
