# Generated by Django 5.0.1 on 2024-05-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0034_alter_write_off_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='write_off_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Baixa'),
        ),
    ]
