# Generated by Django 5.0.1 on 2024-05-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0036_alter_destinations_name_alter_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.destinations', verbose_name='Localização'),
        ),
    ]
