# Generated by Django 5.0.1 on 2024-05-13 15:19

import django.db.models.deletion
import inventory_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0037_productunit_shelf_alter_productunit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='write_off',
            name='transfer_area',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.destinations', verbose_name='Área de transferência'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='location',
            field=models.ForeignKey(default=inventory_management.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.destinations', verbose_name='Localização'),
        ),
    ]
