# Generated by Django 5.0.1 on 2024-05-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0038_write_off_transfer_area_alter_productunit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='write_off',
            name='transfer_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.destinations', verbose_name='Área de transferência'),
        ),
    ]
