# Generated by Django 5.0.1 on 2024-05-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0039_alter_write_off_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothconsumption',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='clothconsumption',
            name='weight_length_after',
        ),
        migrations.AddField(
            model_name='clothconsumption',
            name='remainder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tamanho / Peso Atual'),
        ),
    ]
