# Generated by Django 5.0.1 on 2024-05-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0040_remove_clothconsumption_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='shelf_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_origin', to='inventory_management.shelf', verbose_name='Gaveta de origem'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.destinations', verbose_name='Área de Transferência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='inventory_management.destinations', verbose_name='Origem'),
        ),
    ]
