# Generated by Django 5.0.1 on 2024-05-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0044_remove_destinations_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='shelf_origin',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='transfer_area',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.room', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_transfer_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.transferareas', verbose_name='Área de Transferência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_origin', to='inventory_management.shelf', verbose_name='Gaveta de origem'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='origin_transfer_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='inventory_management.transferareas', verbose_name='Origem'),
            preserve_default=False,
        ),
    ]
