# Generated by Django 5.0.1 on 2024-05-15 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0045_remove_stocktransfer_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination_store',
        ),
        migrations.AddField(
            model_name='productunit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja'),
        ),
    ]
