# Generated by Django 5.0.1 on 2024-05-16 00:46

import django.db.models.deletion
import inventory_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0047_alter_productunit_building_alter_productunit_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='location',
            field=models.ForeignKey(default=inventory_management.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.transferareas', verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta'),
        ),
    ]
