# Generated by Django 5.0.1 on 2024-05-16 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0048_alter_productunit_building_alter_productunit_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Prateleira'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Prateleira'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_origin', to='inventory_management.shelf', verbose_name='Prateleira de origem'),
        ),
    ]
