# Generated by Django 5.0.1 on 2024-05-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0049_alter_productunit_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.room', verbose_name='Sala de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Prateleira de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_transfer_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.transferareas', verbose_name='Destino de Transferência'),
        ),
    ]
