# Generated by Django 5.0.1 on 2024-05-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0050_alter_stocktransfer_destination_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write_off',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='write_off',
            name='recomission_destination',
        ),
        migrations.RemoveField(
            model_name='write_off',
            name='transfer_area',
        ),
        migrations.AddField(
            model_name='productunit',
            name='qr_code_generated',
            field=models.BooleanField(default=False, verbose_name='QR Code Gerado?'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_origin_shelf', to='inventory_management.shelf', verbose_name='Prateleira de origem'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='origin_transfer_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_origin', to='inventory_management.transferareas', verbose_name='Área de transferência'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Loja de Recomissão'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor de Recomissão'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.room', verbose_name='Sala de Recomissão'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Destino da Recomissão'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_transfer_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.transferareas', verbose_name='Área de Recomissão'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin_shelf', to='inventory_management.shelf', verbose_name='Prateleira de origem'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_transfer_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin', to='inventory_management.transferareas', verbose_name='Origem'),
        ),
    ]
