# Generated by Django 5.0.1 on 2024-05-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0051_remove_write_off_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write_off',
            name='origin_shelf',
        ),
        migrations.RemoveField(
            model_name='write_off',
            name='origin_transfer_area',
        ),
        migrations.AddField(
            model_name='write_off',
            name='transfer_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_origin', to='inventory_management.transferareas', verbose_name='Área de transferência'),
        ),
    ]
