# Generated by Django 5.0.1 on 2024-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0053_write_off_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
