# Generated by Django 5.0.1 on 2024-05-24 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0054_alter_write_off_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productunit",
            old_name="imcoming",
            new_name="incoming",
        ),
    ]
