# Generated by Django 5.0.1 on 2024-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0055_rename_imcoming_productunit_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoffdestinations',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Destinatário'),
        ),
    ]
