# Generated by Django 5.0.1 on 2024-06-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0056_alter_writeoffdestinations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin_shelf', to='inventory_management.shelf', verbose_name='Prateleira de origem'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_transfer_area',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin', to='inventory_management.transferareas', verbose_name='Origem'),
        ),
    ]
