# Generated by Django 5.0.1 on 2024-06-03 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0058_alter_stocktransfer_origin_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='recomission_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Prateleira da Recomissão'),
        ),
    ]
