# Generated by Django 5.0.1 on 2024-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0059_alter_write_off_recomission_shelf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='productunit',
            name='was_written_off',
            field=models.BooleanField(default=False, verbose_name='Foi baixado?'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='weight_length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Metro/Kg'),
        ),
    ]
