# Generated by Django 5.0.1 on 2024-06-13 23:57

import django.db.models.deletion
import inventory_management.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0061_alter_productunit_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='origin_transfer_area',
        ),
        migrations.RemoveField(
            model_name='write_off',
            name='recomission_transfer_area',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination_transfer_area',
        ),
        migrations.RemoveField(
            model_name='write_off',
            name='transfer_area',
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('cm', 'Centímetros'), ('m', 'Metros'), ('g', 'Gramas'), ('kg', 'Quilogramas'), ('u', 'Unidade')], max_length=2, verbose_name='Medida'),
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Local')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Área de Transferência',
                'verbose_name_plural': 'Áreas de Transferência',
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_storage_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.storagetype', verbose_name='Destino de Transferência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='origin_storage_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin', to='inventory_management.storagetype', verbose_name='Origem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='write_off',
            name='recomission_storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.storagetype', verbose_name='Área de Recomissão'),
        ),
        migrations.AddField(
            model_name='write_off',
            name='storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_origin', to='inventory_management.storagetype', verbose_name='Área de transferência'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='location',
            field=models.ForeignKey(default=inventory_management.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.storagetype', verbose_name='Localização'),
        ),
        migrations.DeleteModel(
            name='TransferAreas',
        ),
    ]
