# Generated by Django 5.0.1 on 2024-06-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0062_remove_stocktransfer_origin_transfer_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Depósito', 'verbose_name_plural': 'Depósitos'},
        ),
        migrations.AlterModelOptions(
            name='storagetype',
            options={'verbose_name': 'Tipo de Depósito', 'verbose_name_plural': 'Tipos de Depósito'},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Depósito de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.storagetype', verbose_name='Tipo do Depósito de Destino'),
        ),
        migrations.AlterField(
            model_name='write_off',
            name='recomission_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Depósito de Recomissão'),
        ),
        migrations.AlterField(
            model_name='write_off',
            name='storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_origin', to='inventory_management.storagetype', verbose_name='Tipo de depósito'),
        ),
    ]
