# Generated by Django 5.0.1 on 2024-06-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0063_alter_building_options_alter_storagetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='write_off',
            field=models.BooleanField(default=False, verbose_name='Está Baixado?'),
        ),
    ]
