# Generated by Django 5.0.1 on 2024-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0064_alter_productunit_write_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='code',
            field=models.CharField(default=None, editable=False, max_length=8, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
