# Generated by Django 5.0.1 on 2024-06-21 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0065_remove_hall_room_building_has_hall_building_has_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.building', verbose_name='Prédio')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='productunit',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rooms', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rooms', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rooms', verbose_name='Sala de Destino'),
        ),
        migrations.AlterField(
            model_name='write_off',
            name='recomission_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rooms', verbose_name='Sala de Recomissão'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
