# Generated by Django 5.0.1 on 2024-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0065_productunit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
