# Generated by Django 5.0.1 on 2024-06-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0067_stocktransfer_origin_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_off',
            name='recomission_storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomission_destination', to='inventory_management.storagetype', verbose_name='Área de Recomissão'),
        ),
    ]
