# Generated by Django 5.0.1 on 2024-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0068_alter_write_off_recomission_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Transferência'),
        ),
    ]
