# Generated by Django 5.0.1 on 2024-06-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0066_alter_productunit_code'),
        ('inventory_management', '0069_alter_stocktransfer_transfer_date'),
    ]

    operations = [
    ]
