# Generated by Django 5.0.1 on 2024-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0070_merge_20240625_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
