# Generated by Django 5.0.1 on 2024-07-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0071_alter_building_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.hall', verbose_name='Corredor'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.rooms', verbose_name='Sala'),
        ),
    ]
