# Generated by Django 5.0.1 on 2024-07-25 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0072_alter_shelf_hall_alter_shelf_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['name'], 'verbose_name': 'Gaveta', 'verbose_name_plural': 'Gavetas'},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Gaveta'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta de Destino'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origin_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktransfer_origin_shelf', to='inventory_management.shelf', verbose_name='Gaveta de origem'),
        ),
        migrations.AlterField(
            model_name='write_off',
            name='recomission_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.shelf', verbose_name='Gaveta da Recomissão'),
        ),
    ]
