# Generated by Django 5.0.1 on 2024-07-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0073_alter_shelf_options_alter_productunit_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='weight_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metro/Kg'),
        ),
    ]
