# Generated by Django 5.0.1 on 2024-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0075_alter_color_options_alter_pattern_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetype',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='É Loja?'),
        ),
    ]
