# Generated by Django 5.0.1 on 2024-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0076_storagetype_is_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor'),
        ),
    ]
