# Generated by Django 5.0.1 on 2024-09-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0077_productunit_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Lojas', 'verbose_name_plural': 'Loja'},
        ),
    ]
