# Generated by Django 5.0.1 on 2024-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0078_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='building',
            name='has_hall',
            field=models.BooleanField(default=True, verbose_name='Possui Corredor?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='has_room',
            field=models.BooleanField(default=True, verbose_name='Possui Sala?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='has_shelf',
            field=models.BooleanField(default=True, verbose_name='Possui Gaveta?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua'),
        ),
    ]
