# Generated by Django 5.0.1 on 2025-01-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0079_alter_building_cep_alter_building_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='write_off',
            options={'permissions': [('can_write_off', 'Can write off'), ('can_recomission', 'Can recomission')], 'verbose_name': 'Baixa', 'verbose_name_plural': 'Baixas'},
        ),
    ]
