# Generated by Django 5.0.1 on 2025-01-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0080_alter_write_off_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_view_admin', 'Can view admin')], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
