# Generated by Django 5.0.1 on 2025-01-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0081_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
