# Generated by Django 5.0.1 on 2025-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0082_remove_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='metro',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
