# Generated by Django 5.0.1 on 2025-02-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0083_productunit_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='metro',
        ),
    ]
