# Generated by Django 5.0.1 on 2025-03-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0085_product_code1_product_code2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'permissions': [('can_view_workspace_write_off', 'Can view workspace write off')], 'verbose_name': 'Área de Trabalho', 'verbose_name_plural': 'Áreas de Trabalho'},
        ),
    ]
